### ISSUE TITLE
Make the image footer optional

### ISSUE THREAD

**Issue by sluongng** [go101/golds#11]
This is a very cool package.

It would be a lot easier to adopt if you make the footer(twitter/wechat) optional.

Better yet, provide a config for user to either turn off the footer or customize their own during deployment.

**Comment by go101** [comment]
Is it ok to add a `-simplefooter` option, if which is specified, a simple footer like "Generated with Golds v0.1.7. (GOOS=linux GOARCH=amd64)" is used instead?

**Comment by go101** [comment]
@sluongng 
Thanks for the suggestion. 

The project will use a configuration file to customize generation outputs when most of planned features are implemented and most command line options are stabilized. Since then, local `go.lds` files and a global one will be looked up and viewed as configuration files. (I opened [another issue](https://github.com/go101/golds/issues/12) for this.)

Currently, (experimental) command line options are preferred. Forks are welcome if these options don't satisfy specific needs.

A `-footer` option will be added soon afterwards.

**Comment by go101** [comment]
A `-footer-showing=verbose+qrcode|verbose|simple|none` cli option is added in v0.1.8.
