### ISSUE TITLE
Feature request: show package documentation by default

### ISSUE THREAD

**Issue by alecthomas** [go101/golds#16]
It seems very strange to me that when I navigate to the documentation for a package, I don't see the actual _documentation_. I have to hunt and expand a tiny `d`. Please consider showing the documentation at the top, similar to how godoc and go.pkg.dev work.

**Comment by go101** [comment]
I will add a hidden option to control this behavior.

I think generally the most important information in a package is the exported types. So I don't want the distance from the type lists to the page top is too far.

**Comment by alecthomas** [comment]
I know you've put a lot of work into this, which I really do appreciate, but I am positive that the lack of _documentation_ in the golds output is actively putting people off. I launched this internally at work for our API docs and the first thing people responded with was "that's unreadable, let's just run a godoc server in Kubernetes". 

The fact is that golds does not succeed at providing the _documentation_ part of API docs. It provides the API only. I love golds. I love the speed, the information it provides, but without actual _documentation_ it's pretty much unusable to the teams at work.

As per #13, I think that emulating godocs output, but with your enhancements added, would be the perfect solution.

**Comment by go101** [comment]
I started develop Golds mainly because I need a better code reader to study some Go projects. 
Other features were added eventually. They were not unplaned at the beginning.
(Don't be worry, these features will be maintained seriously.)

I don't know how many users are using Golds and how many are using the docs generation feature.
I'm only aware of two. Your are one of them and made some great valuable suggestions.
OK, I will change the initial docs showing ways for packages (show full) and identifiers (show one line).

And several hotkeys will be also added eventually to satisfy different needs:
```
p - toggle package docs collapse/expand
t - toggle types docs collapse/expand
f - toggle functions docs collapse/expand
v - toggle variables docs collapse/expand
c - toggle constants docs collapse/expand
a - toggle all docs collapse/expand
```

A right-side nav column might be also be added if I find a good implementation later (very low priority).

Two options will be added later if someone request them:
* `-package-docs-showing-initially=collapse|simple|expand`, the default value is `expand`.
* `-identifier-docs-showing-initially=collapse|oneline|expand`, the default is `oneline`.

**Comment by go101** [comment]
I just pushed a commit which expand top-level docs by default. The hotkeys are also added.

I found there are some UE complexities and difficulties to implement [the one-line docs for identifiers](https://github.com/go101/golds/issues/17).  So I hold it now and hope I could find a clear way to implement it.

**Comment by go101** [comment]
@alecthomas 
As package docs are shown by default. I will close this issue soon.
